version: '3'
services:
  revieee_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: revieee_nginx
    container_name: revieee_nginx_container
    volumes:
      - ./nginx/conf:/usr/local/nginx/conf
      - ./nginx/hook:/usr/local/nginx/hook
    ports:
      - 80:80
